export const REQUEST_LIST_START = 'REQUEST_LIST_START';
export const REQUEST_LIST_SUCCESS = 'REQUEST_LIST_SUCCESS';
export const REQUEST_LIST_FAILED = 'REQUEST_LIST_FAILED';
export const SEARCH_LIST_START = 'SEARCH_LIST_START';
export const SEARCH_LIST_SUCCESS = 'SEARCH_LIST_SUCCESS';
export const SEARCH_LIST_FAILED = 'SEARCH_LIST_FAILED';
